### PR TITLE
fix(fields): resolve flat property keys containing colons

### LINKED ISSUE #771: fix(fields): flat property keys with colons not resolved
## Bug Description
The `tourism_information_office:website` field isn't displayed on POI detail pages, even though the data exists in the API response and the field is configured in `details_fields`.

## Expected Behavior
The field should appear in the `group_tourism_website` card block on the detail page.

## Steps to Reproduce
1. Go to http://city-landes_attractivite_2.localtest.me:3000/poi/62551/details
2. The "tourism website" block is missing
3. The API returns `"tourism_information_office:website": ["https://..."]` in the POI properties

## Root Cause
`utils/property.ts:31` — `getNestedPropertyValue` splits the field path on `/[.:]/`, which breaks flat property keys that contain colons.

For `"tourism_information_office:website"`, it splits into `["tourism_information_office", "website"]` and tries nested access `properties["tourism_information_office"]["website"]` instead of the flat key `properties["tourism_information_office:website"]`.

Since the value resolves to `null`, `isFiledEmpty()` marks the field as empty and the entire group is hidden.

## Proposed Fix
In `getNestedPropertyValue`, try the full path as a direct property key before falling back to nested splitting.

## Files to Modify
- `utils/property.ts` — add direct key lookup before split

### PR DESCRIPTION
**Pull request by wazolab**
## Summary
- `getNestedPropertyValue` splits paths on `.` and `:`, which breaks flat property keys like `tourism_information_office:website`
- Added direct property lookup before falling back to nested splitting
- Fixes the missing tourism website field on POI detail pages

Closes #771

## Test plan
- [ ] Visit http://city-landes_attractivite_2.localtest.me:3000/poi/62551/details — the tourism website block should now appear
- [ ] Verify other fields (phone, email, description, address) still render correctly
- [ ] Verify nested fields (e.g. route GPX trace) still resolve properly

### CODE REVIEW

File: utils/property.ts [hunk 1]
```diff
@@ -27,21 +27,22 @@ export function isFieldMultilingual(editorial: MenuCategoryEditorial, property:
...
-  if (multilingual)
-    value = value?.['fr-FR']
+  for (const key of keys) {
+    if (value == null || typeof value !== 'object')
+      return null
 
-  if (restKeys.length === 0)
-    return value ?? null
+    // Auto-unwrap multilingual intermediate objects (e.g. route: { "fr-FR": { gpx_trace: "..." } })
+    if (!(key in value) && 'fr-FR' in value)
```
Comment (frodrigo) [inline utils/property.ts]: Should check for `multilingual` before 'fr-FR'
